4:
  ai: https://www.collegenote.net/courses/TU/CSIT/30/artificial-intelligence/syllabus/
  dbms: https://www.collegenote.net/courses/TU/CSIT/32/database-management-system/syllabus/
  os: https://www.collegenote.net/courses/TU/CSIT/33/operating-systems/syllabus/
  cn: https://www.collegenote.net/courses/TU/CSIT/31/computer-networks/syllabus/
  toc: https://www.collegenote.net/courses/TU/CSIT/34/theory-of-computation/syllabus/
